Repository moshuying/project-3-crm, pull requests merged in 2021-05, with the labels that each got.

#12 Create blank.yml
  .github/workflows/blank.yml
Labels: enhancement

#13 Create SECURITY.md
  SECURITY.md
Labels: enhancement

#14 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: enhancement

#15 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: enhancement

#16 添加sql文件
  back/mysql/MySQL____localhost__3_-2021_05_15_10_46_18-dump.sql
Labels: enhancement

#18 Fix bug issues #11
  back/src/main/java/com/msy/plus/controller/RoleController.java
  front/src/pages/role/index.vue
Labels: bug, enhancement

#19 添加项目需求文件
  docs/CRM需求模拟.docx
  docs/JAVA实训方案-CRM(10天)-高级.docx
  docs/项目需求文档.docx
Labels: documentation

#20 进入员工管理页面，完善员工管理中较为复杂的员工信息分页查询以及员工信息详情
  back/src/main/java/com/msy/plus/controller/AccountController.java
  back/src/main/java/com/msy/plus/controller/EmployeeController.java
  back/src/main/java/com/msy/plus/entity/Employee.java
  back/src/main/java/com/msy/plus/entity/EmployeeDetail.java
  back/src/main/java/com/msy/plus/entity/EmployeeWithRoleDO.java
  back/src/main/java/com/msy/plus/mapper/EmployeeMapper.java
  back/src/main/java/com/msy/plus/service/EmployeeService.java
  back/src/main/java/com/msy/plus/service/impl/EmployeeServiceImpl.java
  back/src/main/resources/mapper/EmployeeMapper.xml
  back/src/test/java/CodeGenerator.java
  front/src/router/config.js
Labels: documentation, enhancement, good first issue

#21 Create dependabot.yml
  .github/dependabot.yml
Labels: help wanted

#32 Customer manager
  back/src/main/java/com/msy/plus/controller/CustomerManagerController.java
  back/src/main/java/com/msy/plus/dto/CustomerManagerList.java
  back/src/main/java/com/msy/plus/entity/CustomerManager.java
  back/src/main/java/com/msy/plus/mapper/CustomerManagerMapper.java
  back/src/main/java/com/msy/plus/service/CustomerManagerService.java
  back/src/main/java/com/msy/plus/service/impl/CustomerManagerServiceImpl.java
  back/src/main/resources/application-dev.yml
  back/src/main/resources/mapper/CustomerManagerMapper.xml
  back/src/test/java/CodeGenerator.java
  back/src/test/java/JasyptStringEncryptor.java
  front/src/pages/customer/manager.vue
  front/src/router/config.js
  front/src/services/api.js
  front/src/services/customerManager.js
  front/src/services/dictionaryContents.js
  front/src/services/dictionaryDetails.js
  front/src/services/permission.js
Labels: enhancement

#35 修复#34问题
  front/src/pages/employee/index.vue
Labels: bug

#39 Fixbug#37
  back/src/main/java/com/msy/plus/controller/CustomerManagerController.java
  back/src/main/java/com/msy/plus/controller/EmployeeController.java
  back/src/main/java/com/msy/plus/dto/CustomerManagerList.java
  back/src/main/java/com/msy/plus/entity/CustomerManager.java
  back/src/main/java/com/msy/plus/mapper/CustomerManagerMapper.java
  back/src/main/java/com/msy/plus/service/CustomerManagerService.java
  back/src/main/java/com/msy/plus/service/impl/CustomerManagerServiceImpl.java
  back/src/main/resources/application-dev.yml
  back/src/main/resources/mapper/CustomerManagerMapper.xml
  back/src/main/resources/mapper/EmployeeMapper.xml
  back/src/test/java/CodeGenerator.java
  back/src/test/java/JasyptStringEncryptor.java
  front/src/pages/customer/manager.vue
  front/src/pages/employee/index.vue
  front/src/router/config.js
  front/src/services/api.js
  front/src/services/customerManager.js
  front/src/services/dictionaryContents.js
  front/src/services/dictionaryDetails.js
  front/src/services/permission.js
Labels: bug

#41 备份mysql文件
  back/mysql/crm3_localhost-2021_05_21_12_51_26-dump.sql
Labels: documentation, duplicate, enhancement

#43 Customer manager
  back/mysql/crm3_localhost-2021_05_21_12_51_26-dump.sql
  back/src/main/java/com/msy/plus/controller/AccountController.java
  back/src/main/java/com/msy/plus/controller/CustomerHandoverController.java
  back/src/main/java/com/msy/plus/controller/EmployeeController.java
  back/src/main/java/com/msy/plus/core/jwt/JwtUtil.java
  back/src/main/java/com/msy/plus/dto/CustomerManagerList.java
  back/src/main/java/com/msy/plus/entity/AccountDO.java
  back/src/main/java/com/msy/plus/entity/CustomerHandover.java
  back/src/main/java/com/msy/plus/mapper/CustomerHandoverMapper.java
  back/src/main/java/com/msy/plus/mapper/CustomerManagerMapper.java
  back/src/main/java/com/msy/plus/service/CustomerHandoverService.java
  back/src/main/java/com/msy/plus/service/impl/CustomerHandoverServiceImpl.java
  back/src/main/java/com/msy/plus/service/impl/CustomerManagerServiceImpl.java
  back/src/main/java/com/msy/plus/service/impl/EmployeeServiceImpl.java
  back/src/main/resources/mapper/AccountMapper.xml
  back/src/main/resources/mapper/CustomerHandoverMapper.xml
  back/src/main/resources/mapper/CustomerManagerMapper.xml
  back/src/main/resources/mapper/RoleMapper.xml
  back/src/test/java/CodeGenerator.java
  front/src/pages/customer/manager.vue
  front/src/pages/department/index.vue
  front/src/pages/dictionary/contents.vue
  front/src/pages/dictionary/details.vue
  front/src/pages/employee/index.vue
  front/src/pages/permission/index.vue
  front/src/pages/role/index.vue
  front/src/services/api.js
  front/src/services/customerHandover.js
Labels: bug, documentation, duplicate, enhancement, good first issue, help wanted

#46 Follow up history
  back/src/main/java/com/msy/plus/controller/CustomerFollowUpHistoryController.java
  back/src/main/java/com/msy/plus/entity/CustomerFollowUpHistory.java
  back/src/main/java/com/msy/plus/mapper/CustomerFollowUpHistoryMapper.java
  back/src/main/java/com/msy/plus/service/CustomerFollowUpHistoryService.java
  back/src/main/java/com/msy/plus/service/impl/CustomerFollowUpHistoryServiceImpl.java
  back/src/main/resources/mapper/CustomerFollowUpHistoryMapper.xml
  back/src/test/java/CodeGenerator.java
  front/src/pages/customer/manager.vue
  front/src/services/api.js
  front/src/services/customerFollowUpHistory.js
Labels: bug, enhancement

#47 完善潜在客户管理
  back/src/main/java/com/msy/plus/controller/AccountController.java
  back/src/main/java/com/msy/plus/controller/CustomerFollowUpHistoryController.java
  back/src/main/java/com/msy/plus/controller/CustomerHandoverController.java
  back/src/main/java/com/msy/plus/controller/EmployeeController.java
  back/src/main/java/com/msy/plus/core/jwt/JwtUtil.java
  back/src/main/java/com/msy/plus/dto/CustomerManagerList.java
  back/src/main/java/com/msy/plus/entity/AccountDO.java
  back/src/main/java/com/msy/plus/entity/CustomerFollowUpHistory.java
  back/src/main/java/com/msy/plus/entity/CustomerHandover.java
  back/src/main/java/com/msy/plus/mapper/CustomerFollowUpHistoryMapper.java
  back/src/main/java/com/msy/plus/mapper/CustomerHandoverMapper.java
  back/src/main/java/com/msy/plus/mapper/CustomerManagerMapper.java
  back/src/main/java/com/msy/plus/service/CustomerFollowUpHistoryService.java
  back/src/main/java/com/msy/plus/service/CustomerHandoverService.java
  back/src/main/java/com/msy/plus/service/impl/CustomerFollowUpHistoryServiceImpl.java
  back/src/main/java/com/msy/plus/service/impl/CustomerHandoverServiceImpl.java
  back/src/main/java/com/msy/plus/service/impl/CustomerManagerServiceImpl.java
  back/src/main/java/com/msy/plus/service/impl/EmployeeServiceImpl.java
  back/src/main/resources/mapper/AccountMapper.xml
  back/src/main/resources/mapper/CustomerFollowUpHistoryMapper.xml
  back/src/main/resources/mapper/CustomerHandoverMapper.xml
  back/src/main/resources/mapper/CustomerManagerMapper.xml
  back/src/main/resources/mapper/RoleMapper.xml
  back/src/test/java/CodeGenerator.java
  front/src/pages/customer/manager.vue
  front/src/pages/department/index.vue
  front/src/pages/dictionary/contents.vue
  front/src/pages/dictionary/details.vue
  front/src/pages/employee/index.vue
  front/src/pages/permission/index.vue
  front/src/pages/role/index.vue
  front/src/services/api.js
  front/src/services/customerFollowUpHistory.js
  front/src/services/customerHandover.js
Labels: enhancement

#50 Fixbug#45
  back/src/main/java/com/msy/plus/controller/AccountController.java
  back/src/main/java/com/msy/plus/controller/EmployeeController.java
Labels: bug, enhancement

#51 Fixbug#44
  back/src/main/java/com/msy/plus/controller/CustomerFollowUpHistoryController.java
  back/src/main/java/com/msy/plus/controller/CustomerHandoverController.java
  front/src/pages/customer/manager.vue
Labels: bug, documentation

#52 完成正式客户管理页面
  front/src/pages/customer/official.vue
  front/src/pages/employee/index.vue
  front/src/router/config.js
Labels: documentation, help wanted

#59 Cfuh
  back/src/main/resources/mapper/CustomerFollowUpHistoryMapper.xml
  front/src/pages/customer/followHistory.vue
  front/src/pages/customer/manager.vue
Labels: bug, documentation, duplicate, enhancement

#60 客户管理所有功能全部完成
  back/src/main/java/com/msy/plus/controller/CustomerFollowUpHistoryController.java
  back/src/main/java/com/msy/plus/entity/CFUHSearch.java
  back/src/main/java/com/msy/plus/mapper/CustomerFollowUpHistoryMapper.java
  back/src/main/java/com/msy/plus/service/CustomerFollowUpHistoryService.java
  back/src/main/java/com/msy/plus/service/impl/CustomerFollowUpHistoryServiceImpl.java
  back/src/main/resources/mapper/CustomerFollowUpHistoryMapper.xml
  front/src/pages/customer/followHistory.vue
  front/src/pages/customer/manager.vue
  front/src/router/config.js
Labels: documentation, enhancement

#61 Add sql
  back/mysql/MySQL____localhost__3_-2021_05_15_10_46_18-dump.sql
  back/mysql/MySQL____localhost__3_-2021_05_19_11_14_46-dump.sql
  mysql/crm3_localhost-2021_05_22_16_09_10-dump.sql
Labels: documentation

#63 修复员工新增客户数量返回错误
  back/src/main/resources/mapper/CustomerManagerMapper.xml
Labels: bug, documentation

#64 Add sql
  back/src/main/java/com/msy/plus/controller/AnalysisController.java
  back/src/main/java/com/msy/plus/dto/AnalysisQuery.java
  back/src/main/java/com/msy/plus/entity/Analysis.java
  back/src/main/java/com/msy/plus/mapper/CustomerManagerMapper.java
  back/src/main/java/com/msy/plus/service/CustomerManagerService.java
  back/src/main/java/com/msy/plus/service/impl/CustomerManagerServiceImpl.java
  back/src/main/resources/mapper/CustomerManagerMapper.xml
  front/package.json
  front/src/pages/analysis/index.vue
  front/src/pages/components/table/Table.vue
  front/src/pages/customer/followHistory.vue
  front/src/pages/customer/manager.vue
  front/src/pages/customer/official.vue
  front/src/pages/customer/resource.vue
  front/src/pages/detail/AdvancedDetail.vue
  front/src/pages/employee/index.vue
  front/src/pages/role/index.vue
  front/src/router/config.js
  front/src/services/analysis.js
  front/src/services/api.js
  front/src/services/user.js
Labels: bug, documentation, duplicate

#65 完成所有功能
  back/mysql/MySQL____localhost__3_-2021_05_15_10_46_18-dump.sql
  back/mysql/MySQL____localhost__3_-2021_05_19_11_14_46-dump.sql
  back/src/main/java/com/msy/plus/controller/AnalysisController.java
  back/src/main/java/com/msy/plus/dto/AnalysisQuery.java
  back/src/main/java/com/msy/plus/entity/Analysis.java
  back/src/main/java/com/msy/plus/mapper/CustomerManagerMapper.java
  back/src/main/java/com/msy/plus/service/CustomerManagerService.java
  back/src/main/java/com/msy/plus/service/impl/CustomerManagerServiceImpl.java
  back/src/main/resources/mapper/CustomerManagerMapper.xml
  front/package.json
  front/src/pages/analysis/index.vue
  front/src/pages/components/table/Table.vue
  front/src/pages/customer/followHistory.vue
  front/src/pages/customer/manager.vue
  front/src/pages/customer/official.vue
  front/src/pages/customer/resource.vue
  front/src/pages/detail/AdvancedDetail.vue
  front/src/pages/employee/index.vue
  front/src/pages/role/index.vue
  front/src/router/config.js
  front/src/services/analysis.js
  front/src/services/api.js
  front/src/services/user.js
  mysql/crm3_localhost-2021_05_22_16_09_10-dump.sql
Labels: documentation, duplicate, enhancement, help wanted

#66 Update README.md
  README.md
Labels: documentation, duplicate, enhancement

#88 Update README.md
  README.md
Labels: documentation, duplicate
